login/urls.py
from django.urls import path

from login import views

app_name='login'

urlpatterns = [
    path('', views.index, name='mainpage'),
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('confirm/', views.user_confirm ,name='confirm'),
]

mysite/urls.py
import django
from django.contrib import admin
from django.urls import path, include

from login import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login.urls')),
    path('captcha/', include('captcha.urls')),
]

login/models.py
from django.db import models


class User(models.Model):
    gender = (('male', "男"),
              ('female', "女"),)

    name = models.CharField(max_length=128, unique=True)
    password = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    sex = models.CharField(max_length=32, choices=gender, default="男")
    c_time = models.DateTimeField(auto_now_add=True)
    has_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-c_time"]
        verbose_name = "用户"
        verbose_name_plural = "用户"


class ConfirmString(models.Model):
    code = models.CharField(max_length=256)
    user = models.OneToOneField('User', on_delete=models.CASCADE)
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.name + ":  " + self.code

    class Meta:
        ordering = ['-c_time']
        verbose_name = '确认码'
        verbose_name_plural = verbose_name

login/forms.py
from django import forms
from captcha.fields import CaptchaField


# 登录表单类
class UserForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=128, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username', 'autofocus': ''}))
    password = forms.CharField(label='密码', max_length=256,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    captcha = CaptchaField(label='验证码')


# 注册表单类
class RegisterForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )

    username = forms.CharField(label='用户名', max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='密码', max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='确认密码', max_length=256,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='邮箱地址', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='性别', choices=gender)
    captcha = CaptchaField(label='验证码')

login/views.py
import datetime

# from django.conf import settings
from django.shortcuts import render, redirect
from django.urls import reverse

from login import forms
from login.models import User, ConfirmString
import hashlib

from mysite import settings


def hash_code(s, salt='mysite'):
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())
    return h.hexdigest()


def index(request):
    if not request.session.get('is_login', None):  # 未登录时index页面访问限制
        return redirect(reverse('login:index'))
    return render(request, 'login/index.html')


def login(request):
    if request.session.get('is_login', None):  # 不允许重复登录
        return redirect(reverse('login:login'))
    if request.method == "POST":
        # username = request.POST.get('username')
        # password = request.POST.get('password')
        login_form = forms.UserForm(request.POST)
        message = '请检查填写的内容'
        # if username.strip() and password:
        print('11111')
        if login_form.is_valid():
            print('start')
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            print(username, password)
            # 数据合法性校验
            try:
                user = User.objects.get(name=username)
            except:
                message = '用户不存在'
                return render(request, 'login/login.html', locals())
            if not user.has_confirmed:
                message = '该用户还未经过邮件确认'
                return render(request, 'login/login.html', locals())

            if user.password == hash_code(password):  # 登录成功记录账号状态
                request.session['is_login'] = True
                request.session['user_id'] = user.id
                request.session['user_name'] = user.name
                return redirect(reverse('login:index'))
            else:
                message = '密码不正确'
                return render(request, 'login/login.html', locals())
        else:
            return render(request, 'login/login.html', locals())
    login_form = forms.UserForm()
    return render(request, 'login/login.html', locals())


def register(request):
    if request.session.get('is_login', None):
        return redirect(reverse('login:index'))

    if request.method == 'POST':
        register_form = forms.RegisterForm(request.POST)
        message = '请检查填写的内容'
        if register_form.is_valid():
            username = register_form.cleaned_data.get('username')
            password1 = register_form.cleaned_data.get('password1')
            password2 = register_form.cleaned_data.get('password2')
            email = register_form.cleaned_data.get('email')
            sex = register_form.cleaned_data.get('sex')

            if password1 != password2:
                message = '两次密码不一致'
                return render(request, 'login/register.html', locals())
            else:
                same_name_user = User.objects.filter(name=username)
                if same_name_user:
                    message = '用户名已存在'
                    return render(request, 'login/register.html', locals())
                same_email_user = User.objects.filter(email=email)
                if same_email_user:
                    message = '该邮箱已经注册'
                    return render(request, 'login/register.html', locals())
                new_user = User()
                new_user.name = username
                new_user.password = hash_code(password1)
                new_user.email = email
                new_user.sex = sex
                new_user.save()
                # return redirect('/login/')
                code = make_confirm_string(new_user)
                send_email(email, code)
                message = '请前往邮箱确认'
                return render(request, 'login/confirm.html', locals())
        else:
            return render(request, 'login/register.html', locals())
    register_form = forms.RegisterForm()
    return render(request, 'login/register.html', locals())


def make_confirm_string(user):
    now = datetime.datetime.now().strftime('%Y-%m-%d %H-%M-%S')
    code = hash_code(user.name, now)
    ConfirmString.objects.create(code=code, user=user)
    return code


def send_email(email, code):
    from django.core.mail import EmailMultiAlternatives
    subject = '来自www.liujiangblog.com的注册确认邮件'
    text_content = '''感谢注册www.liujiangblog.com，这里是刘江的博客和教程站点，专注于Python、Django和机器学习技术的分享！\
                    如果你看到这条消息，说明你的邮箱服务器不提供HTML链接功能，请联系管理员！'''
    html_content = ''' <p>感谢注册<a href="http://{}/confirm/?code={}" target=blank>www.liujiangblog.com</a>，\
                    这里是刘江的博客和教程站点，专注于Python、Django和机器学习技术的分享！</p>
                    <p>请点击站点链接完成注册确认！</p>
                    <p>此链接有效期为{}天！</p>'''.format('127.0.0.1:8000', code, settings.CONFIRM_DAYS)
    msg = EmailMultiAlternatives(subject, text_content, settings.EMAIL_HOST_USER, (email,))
    msg.attach_alternative(html_content, 'text/html')
    msg.send()


def logout(request):
    if not request.session.get('is_login', None):
        return redirect(reverse('login:login'))

    request.session.flush()
    return redirect(reverse('login:login'))


def user_confirm(request):
    code = request.GET.get('code', None)
    message = ''
    try:
        confirm = ConfirmString.objects.get(code=code)
    except:
        message = '无效的激活码'
        return render(request, 'login/confirm.html', locals())
    c_time = confirm.c_time
    now = datetime.datetime.now()
    if now > c_time + datetime.timedelta(settings.CONFIRM_DAYS):
        confirm.user.delete()
        message = '激活链接已过期， 请重新注册'
        return render(request, 'login/confirm.html', locals())
    else:
        confirm.user.has_confirmed = True
        confirm.user.save()
        confirm.delete()
        message = '激活成功，请登录'
        return render(request, 'login/confirm.html', locals())

login/templates/login/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>账号激活</title>
</head>
<body>
    <h1 style="margin-left: 100px;">{{ message }}</h1>
    <script>
        window.setTimeout("window.locaton='{% url login:confirm %}'", 2000)
    </script>
</body>
</html>

login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        首页
    </title>
</head>
<body>
    <h1>{{ request.session.user_name }}! 欢迎回来</h1>
    <a href="/logout/">登出</a>
</body>
</html>

login/templates/login/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>登陆页</title>
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'login/css/login.css' %}" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="col">
        <form class="form-login" action="{% url 'login:login' %}" method="post">
            {% if login_form.captcha.errors %}
                <div class="alert alert-warning">{{ login_form.captcha.errors }}</div>
            {% elif message %}
                <div class="alert alert-warning">{{ message }}</div>
            {% endif %}

            {% csrf_token %}
            <h3 class="text-center">欢迎登录</h3>
            <div class="form-group">
{#                <label for="id_username">用户名:</label>#}
{#                <input type="text" id="id_username" class="form-control" name="username" placeholder="用户名" autofocus required>#}
                {{ login_form.username.label_tag }}
                {{ login_form.username }}
            </div>
            <div class="form-group">
{#                <label for="id_password">密码:</label>#}
{#                <input type="password" id="id_password" class="form-control" name="password" placeholder="密码" required>#}
                {{ login_form.password.label_tag }}
                {{ login_form.password }}
            </div>
            <div class="form-group">
                    {{ login_form.captcha.label_tag }}
                    {{ login_form.captcha }}
                  </div>
            <div>
                <a href="{% url 'login:register' %}" class="text-success">
                    <ins>新用户注册</ins>
                </a>
                <button type="submit" class="btn btn-primary float-right">登录</button>
            </div>

        </form>
    </div>
</div>
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
<script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
<script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

login/templates/login/register.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- 上述meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <!-- Bootstrap CSS -->
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'login/css/register.css' %}" rel="stylesheet"/>
    <title>注册</title>
</head>
<body>
<div class="container">
    <div class="col">
        <form class="form-register" action="{% url 'login:register' %}" method="post">
            {% csrf_token %}
            {% if register_form.captcha.errors %}
                <div class="alert alert-warning">{{ register_form.captcha.errors }}</div>
            {% elif message %}
                <div class="alert alert-warning">{{ message }}</div>
            {% endif %}
            <h3 class="text-center">欢迎注册</h3>

            <div class="form-group">
                {{ register_form.username.label_tag }}
                {{ register_form.username }}
            </div>

            <div class="form-group">
                {{ register_form.password1.label_tag }}
                {{ register_form.password1 }}
            </div>

            <div class="form-group">
                {{ register_form.password2.label_tag }}
                {{ register_form.password2 }}
            </div>

            <div class="form-group">
                {{ register_form.email.label_tag }}
                {{ register_form.email }}
            </div>

            <div class="form-group">
                {{ register_form.sex.label_tag }}
                {{ register_form.sex }}
            </div>

            <div class="form-group">
                {{ register_form.captcha.label_tag }}
                {{ register_form.captcha }}
            </div>
            <div>
                <a href="{% url 'login:login' %}">
                    <ins>直接登录</ins>
                </a>
                <button type="submit" class="btn btn-primary float-right">注册</button>
            </div>
        </form>
    </div>
</div> <!-- /container -->

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
{#    以下三者的引用顺序是固定的#}
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
<script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
<script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>
</html>